# Generated by Django 4.0.5 on 2022-06-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('mobileid', models.IntegerField(primary_key=True, serialize=False)),
                ('mobilename', models.TextField(max_length=50)),
                ('mobileprice', models.TextField(max_length=50)),
                ('mobilediscription', models.TextField(max_length=50)),
            ],
        ),
    ]
