# Generated by Django 4.0.5 on 2022-06-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_alter_mobile_mobileid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='mobileimage',
            field=models.ImageField(default='No Image', upload_to='Image'),
        ),
    ]
