# Generated by Django 4.0.5 on 2022-06-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_mobile_mobileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='mobileimage',
            new_name='image',
        ),
    ]
