# Generated by Django 4.0.5 on 2022-07-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_mobile_mobiledeliver_mobile_mobileoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='mobiledeliver',
            field=models.CharField(default='after 7 days', max_length=55),
        ),
    ]
