# Generated by Django 4.0.5 on 2022-07-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_remove_showmobile_id_showmobile_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='mobileprice',
            field=models.FloatField(max_length=50),
        ),
        migrations.DeleteModel(
            name='ShowMobile',
        ),
    ]
