# Generated by Django 4.0.5 on 2022-07-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_alter_mobile_mobileprice_delete_showmobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='mobileprice',
            field=models.FloatField(max_length=20),
        ),
    ]
