# Generated by Django 4.0.5 on 2022-07-28 17:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateField(default=datetime.datetime(2022, 7, 28, 17, 56, 20, 96480, tzinfo=utc))),
                ('orderstatus', models.CharField(default='panding', max_length=50)),
                ('billamount', models.FloatField()),
                ('productlist', models.ManyToManyField(to='cartapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
