# Generated by Django 4.0.5 on 2022-07-30 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_alter_order_orderdate_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='mobile_no',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateField(default=datetime.datetime(2022, 7, 31, 2, 45, 27, 168214)),
        ),
    ]
