# Generated by Django 4.0.5 on 2022-07-31 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_rename_mobile_no_address_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='first_name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='last_name',
            new_name='LastName',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderdate',
            field=models.DateField(default=datetime.datetime(2022, 7, 31, 16, 45, 4, 499895)),
        ),
    ]
